name = "OkAoGTutorials"
uuid = "9aefe428-500e-4e3b-8a70-3d1123ddf76f"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
